- name: Create scripts directory
  file:
    path: /opt/scripts
    state: directory
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true
  notify:
    - Add another bin dir to system-wide $PATH

- name: Install .bash_aliases
  template:
    src: .bash_aliases.j2
    dest: /home/{{ main_username }}/.bash_aliases
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
  become: true

- name: Download docker-compose wrapper
  become: true
  get_url:
    url: https://raw.githubusercontent.com/linuxserver/docker-docker-compose/master/run.sh
    dest: /usr/local/bin/docker-compose
    mode: "0744"
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
    force: "yes"

- name: Download pullio
  become: true
  get_url:
    url: https://raw.githubusercontent.com/hotio/pullio/master/pullio.sh
    dest: /usr/local/bin/pullio
    mode: "0744"
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
    force: "yes"

- name: Move scripts
  template:
    src: files/{{ item }}
    dest: /opt/scripts/{{ item | splitext | first }}
    mode: "0751"
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
  become: true
  loop:
    - backup.sh

- name: Adds cron entry for pullio
  ansible.builtin.cron:
    name: pullio daily
    minute: "0"
    hour: "12"
    job: pullio --tag bb && backup upload > /dev/null
