- name: Create scripts directory
  ansible.builtin.file:
    path: /opt/scripts
    state: directory
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true
  notify:
    - Add another bin dir to system-wide $PATH

- name: Check if .profile exists
  ansible.builtin.stat:
    path: /home/{{ main_username }}/.profile
  register: profile_

- name: Copy .profile
  when: not profile_.stat.exists
  ansible.builtin.copy:
    src: /etc/skel/.profile
    dest: /home/{{ main_username }}/.profile
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
    remote_src: yes

- name: Install .bash_aliases
  ansible.builtin.template:
    src: .bash_aliases.j2
    dest: /home/{{ main_username }}/.bash_aliases
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
  become: true

- name: Configure login for tmux session
  ansible.builtin.blockinfile:
    path: /home/{{ main_username }}/.profile
    marker: "# ANSIBLE MANAGED BLOCK {mark}"
    insertbefore: "# if running bash"
    block: |
      if [[ -z $TMUX ]] && [[ -n $SSH_TTY ]] && [[ -n "$LC_tmux_session" ]] && [[ $- =~ i ]]; then
        session="${LC_tmux_session:-ssh}"
        unset LC_tmux_session

        if tmux has-session -t "$session" 2>/dev/null; then
          exec tmux attach-session -t "$session"
        else
          exec tmux new-session -s "$session"
        fi
      fi

# - name: Download docker compose wrapper
#   become: true
#   ansible.builtin.get_url:
#     url: https://raw.githubusercontent.com/linuxserver/docker-docker compose/master/run.sh
#     dest: /usr/local/bin/docker compose
#     mode: "0744"
#     owner: "{{ main_username }}"
#     group: "{{ main_groupname }}"
#     force: "yes"

- name: Download pullio
  become: true
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hotio/pullio/master/pullio.sh
    dest: /usr/local/bin/pullio
    mode: "0744"
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
    force: "yes"

- name: Check if OMP is installed
  ansible.builtin.stat:
    path: /opt/scripts/oh-my-posh
  register: omp_bin

- name: Check OMP version
  when: omp_bin.stat.exists
  ansible.builtin.command: /opt/scripts/oh-my-posh -version
  register: omp_ver

- name: Get latest release of OMP
  community.general.github_release:
    user: JanDeDobbeleer
    repo: oh-my-posh
    action: latest_release
  register: omp_latest

- name: Download OMP
  when: not omp_bin.stat.exists or omp_latest != ( "v" + omp_ver )
  become: true
  ansible.builtin.get_url:
    url: https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/{{ omp_latest.tag }}/posh-linux-amd64
    dest: /home/{{ main_username }}/.local/bin/oh-my-posh
    mode: "0744"
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
    force: "yes"

- name: Add OMP to bash
  ansible.builtin.lineinfile:
    mode: "0744"
    path: /home/{{ main_username }}/.bashrc
    line: eval "$(oh-my-posh init bash --config {{ secret_posh }})"
    search_string: oh-my-posh
    create: yes

- name: Move scripts
  ansible.builtin.template:
    src: files/{{ item }}
    dest: /opt/scripts/{{ item | splitext | first }}
    mode: "0751"
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
  become: true
  loop:
    - backup.sh

- name: Adds cron entry for pullio
  ansible.builtin.cron:
    name: pullio daily
    minute: "0"
    hour: "12"
    job: /usr/local/bin/pullio --tag bb && /usr/local/bin/backup upload > /dev/null
    user: "{{ main_username }}"
