roles:
  - name: geerlingguy.docker
    version: 7.0.2
  - name: geerlingguy.security
    version: 2.2.2
  - name: geerlingguy.ntp
    version: 2.3.3
  - name: grog.package
    version: v1.4.0
  - name: geerlingguy.pip
    version: 3.0.1
