roles:
  - name: geerlingguy.docker
    version: 7.4.3
  - name: geerlingguy.security
    version: 2.4.0
  - name: geerlingguy.ntp
    version: 2.5.0
  - name: grog.package
    version: v1.4.0
  - name: geerlingguy.pip
    version: 3.1.0
