roles:
  - name: geerlingguy.docker
    version: 6.2.0
  - name: geerlingguy.security
    version: 2.2.0
  - name: geerlingguy.ntp
    version: 2.3.3
  - name: grog.package
    version: v1.3.1
  - name: geerlingguy.pip
    version: 3.0.1
