- name: Install rclone config file
  template:
    src: "rclone.conf"
    dest: "{{ appdata_path }}/rclone/config/rclone.conf"
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
  become: true
