- name: Check config file
  ansible.builtin.stat:
    path: "{{ appdata_path }}/rclone/config/rclone.conf"
  register: rclone_conf

- name: Install rclone config file
  when: not rclone_conf.stat.exists
  ansible.builtin.template:
    src: rclone.conf
    dest: "{{ appdata_path }}/rclone/config/rclone.conf"
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
  become: true
