- name: Move confs
  copy:
    src: "{{ item }}"
    dest: "{{ appdata_path }}/swag/config/nginx/proxy-confs/"
    mode: "0664" # To prevent unnessecary restart after the container has done its chmod
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
  become: true
  register: confs
  with_fileglob:
    - confs/*

- name: Check dns file
  stat:
    path: "{{ appdata_path }}/swag/config/dns-conf/cloudflare.ini"
  register: cf_ini

- name: Install swag dns file
  template:
    src: "files/cloudflare.ini"
    dest: "{{ appdata_path }}/swag/config/dns-conf/cloudflare.ini"
    mode: "600" # To prevent unnessecary nag in logs
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
  become: true

- name: Restart swag
  when: confs.changed or cf_ini.changed
  shell:
    chdir: "{{ appdata_path }}/swag"
    cmd: "{{ docker_update_command }}"
