- name: Create {{ docker_service }} directory # noqa name[template]
  ansible.builtin.file:
    path: "{{ appdata_path }}/{{ docker_service }}"
    state: directory
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Read {{ docker_service }} compose defintion # noqa name[template]
  ansible.builtin.include_vars:
    file: files/{{ docker_service }}.yml
    name: compose

- name: Install {{ docker_service }} compose file # noqa name[template]
  ansible.builtin.template:
    src: common_compose.yml.j2
    dest: "{{ appdata_path }}/{{ docker_service }}/docker-compose.yml"
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
    validate: docker-compose -f %s config
  notify:
    - Restart {{ docker_service }}
  become: true
