- name: Move update script
  register: update
  ansible.builtin.copy:
    src: update.sh
    dest: "{{ appdata_path }}/webhook/config/update.sh"
    mode: "0751"
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
  notify: Restart webhook after config change

- name: Create hooks file
  register: hooks
  ansible.builtin.template:
    src: hooks.json
    dest: "{{ appdata_path }}/webhook/config/hooks/hooks.json"
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
  notify: Restart webhook after config change
