# Dynamic Configuration
http:
  routers:
    dash:
      entryPoints: dash
      rule: "Host(`dir.{{ DOMAIN }}`)"
      service: api@internal

  middlewares:
    home-block:
      ipWhiteList:
        sourceRange: "{{ HomeIp }}"
    gzip:
      compress: {}
    org-admin:
      forwardauth:
        address: https://org.roxedus.net/api/v2/auth?group=1
        # trustForwardHeader: true
        # authresponseheaders: Remote-User, Remote-Groups
