# Dynamic Configuration
http:
  routers:
    dash:
      entryPoints: dash
      rule: "Host(`dir.{{ DOMAIN }}`)"
      service: api@internal

  middlewares:
    home-block:
      ipWhiteList:
        sourceRange: "{{ HomeIp }}"
    gzip:
      compress: {}
