# Dynamic Configuration
http:
  middlewares:
    gzip:
      compress: {}
    org-admin:
      forwardauth:
        address: https://org.roxedus.net/api/v2/auth?group=1
        # trustForwardHeader: true
        # authresponseheaders: Remote-User, Remote-Groups
