# Dynamic Configuration
http:
  routers:
    dash:
      entryPoints: dash
      rule: "Host(`dir.{{ DOMAIN }}`)"
      service: api@internal

  middlewares:
    subfilter-grafana:
      plugin:
        subfilter:
          lastModified: true
          filters:
            regex: "</head>"
            replacement: '<link rel="stylesheet" type="text/css" href="https://gilbn.github.io/theme.park/CSS/themes/grafana/plex.css"></head>'
    home-block:
      ipWhiteList:
        sourceRange: "{{ secret_traefik.homeIp }}"
    gzip:
      compress: {}
    org-admin:
      forwardauth:
        address: https://org.roxedus.net/api/v2/auth?group=1
        # trustForwardHeader: true
        # authresponseheaders: Remote-User, Remote-Groups
