- name: Clickhouse conf
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ appdata_path }}/plausible/"
    mode: "644"
    group: "{{ main_groupname }}"
  become: true
  with_fileglob:
    - "*.xml"
