version: "3.5"

services:
  authentik_ldap:
    container_name: authentik_ldap
    image: ghcr.io/goauthentik/ldap:2022.1.4
    environment:
      - AUTHENTIK_HOST={{ secret_authentik.ldap.host }}
      - AUTHENTIK_INSECURE="false"
      - AUTHENTIK_TOKEN={{ secret_authentik.ldap.token }}
