version: "2.4"
_skip_globals: ["volumes"]

services:
  cfddns:
    container_name: cfddns
    image: ghcr.io/hotio/cloudflareddns
    environment:
      - CF_USER={{ secret_cloudflare.email }}
      - CF_APITOKEN={{ secret_cloudflare[DOMAIN].apikey }}
      - CF_APITOKEN_ZONE={{ secret_cloudflare[DOMAIN].zones }}
      - CF_ZONES={{ secret_cloudflare[DOMAIN].zones }}
      - CF_HOSTS=bot.{{ DOMAIN }}
      - CF_RECORDTYPES=A
      - APPRISE="discord://{{ secret_discord_webook }}?avatar_url=https://logodix.com/logo/1920722.png"
    restart: always
  cfddns_sh:
    container_name: cfddns_sh
    image: ghcr.io/hotio/cloudflareddns
    environment:
      - CF_APITOKEN={{ secret_cloudflare["selfhosters.net"].apikey }}
      - CF_APITOKEN_ZONE={{ secret_cloudflare["selfhosters.net"].zones }}
      - CF_ZONES={{ secret_cloudflare["selfhosters.net"].zones }}
      - CF_HOSTS=bin.selfhosters.net
      - CF_RECORDTYPES=A
      - APPRISE="discord://{{ secret_discord_webook }}?avatar_url=https://logodix.com/logo/1920722.png"
    restart: always
