_skip_globals: [volumes]

services:
  grafana:
    image: grafana/grafana:8.3.4
    container_name: grafana
    user: 1000:1000
    networks:
      - rp-net
      - default
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=BotBox
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-worldmap-panel,grafana-piechart-panel
      - GF_LOG_MODE=console file # f2b things
      - GF_LOG_FILE_LEVEL=error # f2b things
      - GF_LOG_CONSOLE_LEVEL=info # f2b things
      - GF_SECURITY_ADMIN_USER=Roxedus
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SECURITY_COOKIE_SECURE=true
    volumes:
      - "{{ appdata_path }}/{{ docker_service }}/[service_name]/logs:/var/log/grafana"
      - "{{ appdata_path }}/{{ docker_service }}/[service_name]/data:/var/lib/grafana"
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.entrypoints=web-secure
      - traefik.http.routers.grafana.middlewares=org-admin@file

  influx:
    image: influxdb:1.8.10
    container_name: influx
    user: 1000:1000
    volumes:
      - "{{ appdata_path }}/{{ docker_service }}/[service_name]/data:/var/lib/influxdb"
    environment:
      - INFLUXDB_ADMIN_PASSWORD={{ secret_sudo }}
      - INFLUXDB_UDP_ENABLED=true
      - INFLUXDB_UDP_DATABASE=traefik
    networks:
      - rp-net
      - default

networks:
  default:
    external:
      name: grafana
  rp-net:
    external:
      name: intranet
