_skip_globals: [volumes]

services:
  hawkbot:
    container_name: hawkbot
    image: ghcr.io/phasecorex/red-discordbot:full
    volumes:
      - "{{ appdata_path }}/{{ docker_service }}/[service_name]/data:/data"
    environment:
      - PREFIX=-
      - TOKEN={{ secret_bots.hawkbot.token }}
      - STORAGE_TYPE=json

networks:
  default:
    name: hawkbot
