_skip_globals: [volumes, restart]

services:
  monitorrs:
    container_name: rss_bot
    image: synzen/monitorss@sha256:4eeb28e5df07686c724e7dbb470b6cd8c91e0aa9c9b5f11dde75b7880232454d
    depends_on:
      - mongodb
    environment:
      - DRSS_BOT_OWNERIDS=120970603556503552
      - DRSS_BOT_PREFIX=\
      - DRSS_BOT_TOKEN={{ secret_bots.rss.token }}
      - DRSS_DATABASE_URI=mongodb://mongodb_rss:27017/drss
      - DRSS_FEEDS_REFRESHRATEMINUTES=15
      - DRSS_FEEDS_SENDFIRSTCYCLE=true
      - DRSS_FEEDS_SENDOLDONFIRSTCYCLE=true
      - DRSS_LOG_LEVEL=debug
      - DRSS_START=bot
    networks:
      - default
      - rp-net
  rss:
    container_name: rss_web
    image: synzen/monitorss@sha256:4eeb28e5df07686c724e7dbb470b6cd8c91e0aa9c9b5f11dde75b7880232454d
    depends_on:
      - mongodb
      - redis
      - monitorrs
    environment:
      - DRSS_START=web
      - DRSSWEB_LOG_LEVEL=debug
      - DRSSWEB_BOT_CLIENTID={{ secret_bots.rss.client_id }}
      - DRSSWEB_BOT_CLIENTSECRET={{ secret_bots.rss.client_secret }}
      - DRSSWEB_BOT_REDIRECTURI=https://rss.roxedus.net/authorize
      - DRSSWEB_BOT_TOKEN={{ secret_bots.rss.token }}
      - DRSSWEB_DATABASE_REDIS=redis://redis:6379
      - DRSSWEB_DATABASE_URI=mongodb://mongodb_rss:27017/drss
      - DRSSWEB_HTTP_PORT=8080
      - DRSSWEB_TRUSTPROXY_PORT=True
    networks:
      - default
      - rp-net
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:$${DRSSWEB_HTTP_PORT} || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - autoheal=true
      - traefik.enable=true
      - traefik.http.routers.rss.entrypoints=web-secure
      - traefik.http.services.rss.loadbalancer.server.port=8080
      # - traefik.http.routers.rss.middlewares=org-admin@file
  redis:
    container_name: redis
    image: redis:7.0.5-alpine
    user: 1000:1000
    volumes:
      - "{{ appdata_path }}/{{ docker_service }}/[service_name]:/data"
      - /etc/passwd:/etc/passwd:ro
  mongodb:
    container_name: mongodb_rss
    image: mongo:5.0.12
    user: 1000:1000
    volumes:
      - "{{ appdata_path }}/{{ docker_service }}/[service_name]:/data/db"
      - /etc/passwd:/etc/passwd:ro

networks:
  default:
    name: rss
  rp-net:
    name: intranet
    external: true
