_skip_globals: [volumes]

services:
  views:
    container_name: plausible
    image: plausible/analytics:v2.0
    command: sh -c "/entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plaus_db
      - clickhouse

    networks:
      - default
      - rp-net

    labels:
      - traefik.enable=true
      - traefik.http.routers.views.entrypoints=web-secure

      - traefik.http.routers.hosted.rule=Host(`hosted.{{site_domain}}`)
      - traefik.http.routers.hosted.service=views-plausible

      - traefik.http.middlewares.views-index.replacepathregex.regex=/js/index.js
      - traefik.http.middlewares.views-index.replacepathregex.replacement=/js/plausible.js
      - traefik.http.routers.hosted.middlewares=views-index

    environment:
      - SECRET_KEY_BASE={{ secret_plausible.key }}
      - SIGNING_SALT={{ secret_plausible.salt }}
      - DATABASE_URL=postgres://{{ secret_plausible.db.username }}:{{ secret_plausible.db.password }}@plaus_db:5432/{{ secret_plausible.db.name }}
      - DISABLE_REGISTRATION=true
      - DISABLE_SUBSCRIPTION=true
      - CLICKHOUSE_DATABASE_URL=http://clickhouse:8123/plausible
      - BASE_URL=https://views.{{site_domain}}
      - MAILER_EMAIL=noreply@{{ secret_maddy.hostname }}
      - SMTP_HOST_ADDR=maddy
      - SMTP_HOST_PORT=25
      - GOOGLE_CLIENT_ID={{ secret_plausible.google.client_id }}
      - GOOGLE_CLIENT_SECRET={{ secret_plausible.google.client_secret }}

  clickhouse:
    image: clickhouse/clickhouse-server:24.12-alpine
    user: 1000:1000
    container_name: clickhouse
    volumes:
      - "{{ appdata_path }}/{{ docker_service }}/[service_name]:/var/lib/clickhouse"
      - "{{ appdata_path }}/{{ docker_service }}/docker_related_config.xml:/etc/clickhouse-server/config.d/docker_related_config.xml:ro"
      - "{{ appdata_path }}/{{ docker_service }}/docker_related_user_config.xml:/etc/clickhouse-server/users.d/docker_related_user_config.xml:ro"
    tmpfs:
      - /var/log/clickhouse-server
      - /var/log/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plaus_db:
    image: postgres:14.18-alpine
    container_name: plaus_db
    user: 1000:1000
    volumes:
      - "{{ appdata_path }}/{{ docker_service }}/[service_name]:/var/lib/postgresql/data"
      - "{{ appdata_path }}/{{ docker_service }}/[service_name]_migration:/migration"
      - /etc/passwd:/etc/passwd:ro
    environment:
      - POSTGRES_PASSWORD={{ secret_plausible.db.password }}
      - POSTGRES_USER={{ secret_plausible.db.username }}

# Migration notes
# pg_dumpall -U $POSTGRES_USER > /migration/data.sql
# psql -U $POSTGRES_USER < /migration/data.sql
# psql -U $POSTGRES_USER ALTER ROLE {{ secret_plausible.db.name }} PASSWORD '{{ secret_plausible.db.password }}';

networks:
  default:
    name: plausible
    labels:
      com.docker.compose.network: default
  rp-net:
    name: intranet
    external: true
