_skip_globals: [volumes]

services:
  privatebin:
    container_name: privatebin
    image: privatebin/pdo:1.7.5
    # user: 1000:1000
    read_only: true
    depends_on:
      - privatebin_db

    networks:
      - default
      - rp-net

    labels:
      - traefik.enable=true
      - traefik.http.routers.privatebin.entrypoints=web-secure
      - traefik.http.routers.privatebin.rule=Host(`bin.selfhosters.net`)
      - traefik.http.services.privatebin.loadbalancer.server.port=8080
      - traefik.http.routers.privatebin.tls.certresolver=sh_web
    tmpfs:
      - /tmp
      - /var/lib/nginx/tmp
    volumes:
      - "{{ appdata_path }}/{{ docker_service }}/conf.php:/srv/cfg/conf.php:ro"
      - "{{ appdata_path }}/{{ docker_service }}/php.ini:/etc/php8/conf.d/php.ini:ro"
      - "{{ appdata_path }}/{{ docker_service }}/[service_name]:/srv/data"

  privatebin_db:
    image: postgres:14.15-alpine
    container_name: privatebin_db
    user: 1000:1000
    volumes:
      - "{{ appdata_path }}/{{ docker_service }}/[service_name]:/var/lib/postgresql/data"
      - "{{ appdata_path }}/{{ docker_service }}/[service_name]_migration:/migration"
      - /etc/passwd:/etc/passwd:ro
    environment:
      - POSTGRES_PASSWORD={{ secret_privatebin.db.password }}
      - POSTGRES_USER={{ secret_privatebin.db.username }}

networks:
  default:
    internal: true
    labels:
      com.docker.compose.network: default
  rp-net:
    name: intranet
    external: true
