version: "2.4"
_skip_globals: ["volumes"]

services:
  progbot:
    container_name: progbott
    image: ghcr.io/norsk-programmering/progbott:latest
    volumes:
      - "{{ appdata_path }}/progbot/data:/data"
    command: --debug
    labels:
      - traefik.enable=true
      - traefik.http.routers.progbot.entrypoints=web-secure
      - traefik.http.services.progbot.loadbalancer.server.port=5000
