version: "2.4"
_skip_globals: ["volumes"]

services:
  progbot:
    container_name: progbott
    image: ghcr.io/norsk-programmering/progbott@sha256:67001e9182ca669a3c6d714e4bc2748c5eb113c069c568e8c132058a125f464b
    volumes:
      - "{{ appdata_path }}/progbot/data:/data"
    command: --debug
    labels:
      - traefik.enable=true
      - traefik.http.routers.progbot.entrypoints=web-secure
      - traefik.http.services.progbot.loadbalancer.server.port=5000
