version: "2.4"
_skip_globals: ["volumes"]

services:
  progbot:
    container_name: progbott
    image: ghcr.io/norsk-programmering/progbott@sha256:5a836568c66b0658c532a056106c8185f491db305c5e25c492d585f0aee41d7e
    volumes:
      - "{{ appdata_path }}/progbot/data:/data"
    command: --debug
    labels:
      - traefik.enable=true
      - traefik.http.routers.progbot.entrypoints=web-secure
      - traefik.http.services.progbot.loadbalancer.server.port=5000
