_skip_globals: [volumes]

services:
  publisher:
    container_name: publisher
    image: si0972/discordpublisher
    environment:
      - token={{ secret_bots.publisher.token }}
      - prefixes=*
    command: --debug
