_skip_globals: [lables, restart]

services:
  rclone:
    container_name: rclone
    restart: no
    image: ghcr.io/hotio/rclone
    environment:
      - RCLONE_CONFIG=/config/rclone.conf
    volumes:
      - "{{ backup_path }}:{{ backup_path }}"
