version: "2.4"
_skip_globals: ["lables"]

services:
  rclone:
    container_name: rclone
    image: hotio/rclone
    environment:
      - RCLONE_CONFIG=/config/rclone.conf
    volumes:
      - "{{ backup_path }}={{ backup_path }}"
