_skip_globals: [volumes]

services:
  shite:
    container_name: shite
    depends_on:
      - lavalink
      - lavalink_dev
    image: rnorge/music:dev
    environment:
      - debug=true
    volumes:
      - "{{ appdata_path }}/{{ docker_service }}/[service_name]/config:/config"
  lavalink:
    container_name: lavalink
    image: fredboat/lavalink:master
    mem_limit: 800mb # Pesky Java app
    volumes:
      - "{{ appdata_path }}/{{ docker_service }}/[service_name]/application.yml:/opt/Lavalink/application.yml"
  lavalink_dev:
    container_name: lavalink_dev
    image: fredboat/lavalink:dev
    mem_limit: 800mb # Pesky Java app
    volumes:
      - "{{ appdata_path }}/{{ docker_service }}/[service_name]/application.yml:/opt/Lavalink/application.yml"

networks:
  default:
    name: shitenet
