version: "2.4"
services:
  swag:
    container_name: swag
    image: ghcr.io/linuxserver/swag
    environment:
      - EMAIL={{ secret_cloudflare.email }}
      - URL={{ DOMAIN }}
      - SUBDOMAINS=wildcard
      - ONLY_SUBDOMAINS=false
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - MAXMINDDB_LICENSE_KEY={{ secret_cloudflare.maxmind }}
    ports:
      - 80:80
      - 443:443
    cap_add:
      - NET_ADMIN
