version: "2.4"
_skip_globals: [volumes]

services:
  unraider:
    container_name: unraider
    image: ghcr.io/phasecorex/red-discordbot:full
    volumes:
      - "{{ appdata_path }}/{{ docker_service }}/data:/data"
    environment:
      - PREFIX=.
      - TOKEN={{ secret_bots.unraider.token }}
