version: "2.4"

services:
  xbb:
    container_name: static-host
    image: ghcr.io/linuxserver/nginx
    environment:
      - "XBB_URL=https:\\/\\/images.roxedus.net"
      - "XBB_NAME=Roxedus\\\\'s images"
      - "DOCKER_MODS=roxedus/lsio-docker-mods:nginx-xbackbone-latest"
      - "MAXMINDDB_LICENSE_KEY={{ secret_cloudflare.maxmind }}"
    labels:
      - traefik.enable=true
      - traefik.http.routers.xbb.entrypoints=web-secure
      - "traefik.http.routers.xbb.rule=Host(`images.{{ DOMAIN }}`) || Host(`img.{{ DOMAIN }}`)"
