- stat:
    path: "{{ appdata_path }}/traefik/config/traefik.yml"
  register: traefik_before

- name: Traefik conf
  template:
    src: "{{ item }}"
    dest: "{{ appdata_path }}/traefik/config/"
    mode: "600" # To prevent unnessecary nag in logs
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
  become: true
  with_fileglob:
  - "*.yml"

- stat:
    path: "{{ appdata_path }}/traefik/config/traefik.yml"
  register: traefik_after


- name: restart traefik after config change
  when: traefik_before.stat.checksum != traefik_after.stat.checksum
  shell:
    cmd: docker restart traefik