- name: Traefik conf
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ appdata_path }}/traefik/config/"
    mode: "600" # To prevent unnessecary nag in logs
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
  become: true
  with_fileglob:
    - "*.yml"
  notify: Restart traefik after config change
