name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, edited]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2

      - name: Set up Python
        uses: actions/setup-python@v3.1.2
        with:
          python-version: 3.9

      - name: Install linters
        run: |
          pip install $(grep wheel requirements.txt)
          pip install $(grep ansible requirements.txt)
          pip install $(grep ansible-lint requirements.txt)
          pip install $(grep yamllint requirements.txt)

      - name: Lint YAML files
        run: yamllint .

      - name: Lint Ansible files
        run: ansible-lint -p
